using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using QTPlugin;
using QTTabBarLib.Interop;

namespace QTTabBarLib {
    internal static class ButtonBarOperationalController {
        internal static void UnloadInactivePlugins(IntPtr explorerHandle) { QTButtonBarOperationalActions.UnloadInactivePlugins(explorerHandle); }
        internal static void OpenUserAppSubdirectory(DropDownMenuReorderable menu, object sender) { QTButtonBarOperationalActions.OpenUserAppSubdirectory(menu, sender); }
        internal static bool FocusSearchBox(ToolStripSearchBox searchBox) { return QTButtonBarOperationalActions.FocusSearchBox(searchBox); }
        internal static bool RefreshButtons(ToolStripClasses toolStrip, DropDownMenuBase navigation, DropDownMenuReorderable groups, DropDownMenuReorderable recentlyClosed, DropDownMenuReorderable userApps, IntPtr explorerHandle) { return QTButtonBarOperationalActions.RefreshButtons(toolStrip, navigation, groups, recentlyClosed, userApps, explorerHandle); }
        internal static bool SetSearchBarText(ToolStripSearchBox searchBox, string text) { return QTButtonBarOperationalActions.SetSearchBarText(searchBox, text); }
        internal static bool UpdatePluginItem(ToolStripClasses toolStrip, IntPtr explorerHandle, string pid, IBarButton instance, bool enabled, bool refreshImage) { return QTButtonBarOperationalActions.UpdatePluginItem(toolStrip, explorerHandle, pid, instance, enabled, refreshImage); }
        internal static bool TryProcessWindowMessage(ref Message message, IntPtr handle, ShellContextMenu shellContextMenu, ToolStripClasses toolStrip, DropDownMenuReorderable groups, DropDownMenuReorderable userApps, DropDownMenuReorderable recentlyClosed) { return QTButtonBarOperationalActions.TryProcessWindowMessage(ref message, handle, shellContextMenu, toolStrip, groups, userApps, recentlyClosed); }
        internal static void RefreshHeight(Control control) { QTButtonBarOperationalActions.RefreshHeight(control); }
    }

    internal static class QTButtonBarOperationalActions {
        internal static void UnloadInactivePlugins(IntPtr explorerHandle) { QTTabBarClass tabbar = TabInstanceRegistry.GetThreadTabBar(); if(tabbar == null) return; foreach(Plugin plugin in tabbar.pluginServer.Plugins) { PluginType type = plugin.PluginInformation.PluginType; string id = plugin.PluginInformation.PluginID; if(type == PluginType.Interactive) { if(!Config.BBar.ActivePluginIDs.Contains(id)) tabbar.pluginServer.UnloadPluginInstance(id, EndCode.Unloaded); } else if((type == PluginType.Background || type == PluginType.BackgroundMultiple) && plugin.BackgroundButtonEnabled && !Config.BBar.ActivePluginIDs.Contains(id)) { try { if(plugin.Instance != null) plugin.Instance.Close(EndCode.Hidden); } catch(Exception ex) { PluginManager.HandlePluginException(ex, explorerHandle, plugin.PluginInformation.Name, "Closing plugin button. (EndCode.Hidden)"); } plugin.BackgroundButtonEnabled = false; } } }
        internal static void OpenUserAppSubdirectory(DropDownMenuReorderable menu, object sender) { menu.Close(); using(IDLWrapper wrapper = new IDLWrapper(((QMenuItem)sender).Path)) TabInstanceRegistry.GetThreadTabBar().OpenNewTabOrWindow(wrapper); }
        internal static bool FocusSearchBox(ToolStripSearchBox searchBox) { if(searchBox != null) searchBox.TextBox.Focus(); return true; }
        internal static bool RefreshButtons(ToolStripClasses toolStrip, DropDownMenuBase navigation, DropDownMenuReorderable groups, DropDownMenuReorderable recentlyClosed, DropDownMenuReorderable userApps, IntPtr explorerHandle) { Close(navigation); Close(groups); Close(recentlyClosed); Close(userApps); QTTabBarClass tabbar = TabInstanceRegistry.GetThreadTabBar(); int index = tabbar == null ? 0 : tabbar.SelectedTabIndex, count = tabbar == null ? 0 : tabbar.TabCount; if(toolStrip == null) return true; foreach(ToolStripItem item in toolStrip.Items) { if(item == null || item.Tag == null) continue; switch((int)item.Tag) { case QTButtonBar.BII_NAVIGATION_BACK: item.Enabled = tabbar.CanNavigateBackward; break; case QTButtonBar.BII_NAVIGATION_FWRD: item.Enabled = tabbar.CanNavigateForward; break; case QTButtonBar.BII_CLOSE_LEFT: item.Enabled = index > 0; break; case QTButtonBar.BII_CLOSE_RIGHT: item.Enabled = index < count - 1; break; case QTButtonBar.BII_CLOSE_CURRENT: case QTButtonBar.BII_CLOSE_ALLBUTCURRENT: item.Enabled = count > 1; break; case QTButtonBar.BII_GROUP: item.Enabled = GroupsManager.GroupCount > 0; break; case QTButtonBar.BII_APPLICATIONLAUNCHER: item.Enabled = AppsManager.UserApps.Any(); break; case QTButtonBar.BII_RECENTTAB: item.Enabled = StaticReg.ClosedTabHistoryList.Count > 0; break; case QTButtonBar.BII_TOPMOST: ((ToolStripButton)item).Checked = PInvoke.Ptr_OP_AND(PInvoke.GetWindowLongPtr(explorerHandle, -20), 8) == new IntPtr(8); break; } } return true; }
        internal static bool SetSearchBarText(ToolStripSearchBox searchBox, string text) { if(searchBox == null) return false; searchBox.Focus(); searchBox.Text = text ?? string.Empty; return true; }
        internal static bool UpdatePluginItem(ToolStripClasses toolStrip, IntPtr explorerHandle, string pid, IBarButton instance, bool enabled, bool refreshImage) { int p = Array.IndexOf(Config.BBar.ActivePluginIDs, pid); if(p == -1) return false; ToolStripItem item = toolStrip.Items.Cast<ToolStripItem>().FirstOrDefault(value => (int)value.Tag == ((p + 1) << 16)); if(item == null) return false; item.Enabled = enabled; try { item.ToolTipText = instance.Text; if(refreshImage) item.Image = instance.GetImage(Config.BBar.LargeButtons); } catch(Exception ex) { PluginManager.HandlePluginException(ex, explorerHandle, pid, "Refreshing plugin image and text."); } return true; }
        internal static bool TryProcessWindowMessage(ref Message message, IntPtr handle, ShellContextMenu menu, ToolStripClasses strip, DropDownMenuReorderable groups, DropDownMenuReorderable apps, DropDownMenuReorderable recent) { switch(message.Msg) { case 0x117: case 0x2B: case 0x2C: return message.HWnd == handle && menu.TryHandleMenuMsg(message.Msg, message.WParam, message.LParam); case 0x233: PInvoke.SendMessage(TabInstanceRegistry.GetThreadTabBar().Handle, 0x233, message.WParam, IntPtr.Zero); return true; case 0x8000: message.Result = strip.IsHandleCreated ? strip.Handle : IntPtr.Zero; return true; case 0x7B: if((groups == null || !groups.Visible) && (apps == null || !apps.Visible) && (recent == null || !recent.Visible)) TabInstanceRegistry.GetThreadTabBar().ShowContextMenu(false); return true; } return false; }
        internal static void RefreshHeight(Control control) { try { control.SuspendLayout(); } catch(COMException ex) { QTLogger.MakeErrorLog(ex); } finally { control.ResumeLayout(); } }
        private static void Close(ToolStripDropDown menu) { if(menu != null && menu.Visible) menu.Close(ToolStripDropDownCloseReason.AppClicked); }
    }
}
